### ISSUE TITLE
Fix converting perfusion from NIfTi back to DICOM (or just pass along the selected original perfusion)

### ISSUE THREAD

**Issue by a-musipatla** [cai2r/MSNet-pipeline#1]
The part of the postprocessing pipeline that converts perfusion NIfTi back to DICOM [(this piece of code)](https://github.com/cai2r/MSNet-pipeline/blob/81c5f6676ba57da65a46921cb60be1ddf45035a7/src/postprocessing/postprocess.py#L492), fails. 

- [ ] Reproduce the error by running the pipeline
- [ ] Investigate and Implement fix (possibly a data type issue, or an RGB issue)
- [ ] Confirm that perfusion is accurately converted by opening up the output DICOMS ([Weasis](https://weasis.org/en/index.html) is an easy to use DICOM viewer.

**Comment by jmsocallaghan** [comment]
NifTi to DICOM conversion working in latest commit.
